GET http://localhost:3000/subscribers/12

####

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name":"simple",
    "subscribedToChannel":"web simple"
}

####
GET http://localhost:3000/subscribers/6299178aaa9ae08996fed460
 

####
DELETE http://localhost:3000/subscribers/6299178aaa9ae08996fed460


#####
PATCH  http://localhost:3000/subscribers/62991bf2805108ef717ff96d
Content-Type: application/json

{
    "name":"dfd",
    "subscribedToChannel":"simple"
}

####

POST http://localhost:3000/user
Content-Type: application/json

{
    "name":"moeez",
    "email":"mnnmnzx@gmail.com",
    "password":"123456"
}

####

POST http://localhost:3000/auth
Content-Type: application/json

{
    "email":"ozxxzxx@gmail.com",
    "password":"123456"
}